spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQL81Dialect

server:
  port: 9090

app:
  jwtCookieName: 1a123Fsd
  jwtSecret: 12@asqhgdjJas56&
  jwtExpirationMs: 86400000